INPUT_LENGTH = 28
TIME_LENGTH = 28
N_CLASS = 10
HIDDEN_UNITS = 128
C_L2 = 1e-4
LEARNING_RATE = [1e-1, 1e-2]
ANNEALING_STEP = [30]
BATCH_SIZE = 100
EPOCH = 100

SAVE_DIR = "./Saves/"
SUMMARY_DIR = "./Summary/"
CSV_DIR = "./CSV/"
FIGURE_DIR = "./Figures/"